# Generated by Django 4.1.3 on 2022-11-28 17:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SocialCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('front_message', models.TextField(max_length=250)),
                ('back_message', models.TextField(max_length=250)),
                ('card_color', models.TextField(max_length=200, null=True)),
                ('font', models.CharField(blank=True, choices=[('American', 'AMERICAN'), ('Birckley', 'BIRCKLEY'), ('Brush', 'BRUSH'), ('Comic Sans', 'COMIC SANS'), ('Optima', 'OPTIMA'), ('Spring', 'SPRING'), ('Utopia', 'UTOPIA')], max_length=12, null=True)),
                ('text_align', models.CharField(blank=True, choices=[('LEFT', 'LEFT'), ('CENTER', 'CENTER'), ('RIGHT', 'RIGHT')], max_length=50, null=True)),
                ('border_color', models.CharField(choices=[('White', 'WHITE'), ('Red', 'RED'), ('Blue', 'BLUE'), ('Green', 'GREEN'), ('Yellow', 'YELLOW'), ('Pink', 'PINK'), ('Purple', 'PURPLE'), ('Orange', 'ORANGE')], default='ORANGE', max_length=8)),
                ('border_choices', models.CharField(blank=True, choices=[('SOLID', 'Solid'), ('DASHED', 'Dashed'), ('DOTTED', 'Dotted'), ('DOUBLE', 'Double'), ('HAIR', 'Hair'), ('MEDIUM', 'Medium'), ('DASHDOT', 'Dashdot')], max_length=12, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SocialCard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyena.socialcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
