# Generated by Django 4.1.3 on 2022-11-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyena', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialcard',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='border_choices',
            field=models.TextField(blank=True, choices=[('SOLID', 'Solid'), ('DASHED', 'Dashed'), ('DOTTED', 'Dotted'), ('DOUBLE', 'Double'), ('HAIR', 'Hair'), ('MEDIUM', 'Medium'), ('DASHDOT', 'Dashdot')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='border_color',
            field=models.TextField(choices=[('White', 'WHITE'), ('Red', 'RED'), ('Blue', 'BLUE'), ('Green', 'GREEN'), ('Yellow', 'YELLOW'), ('Pink', 'PINK'), ('Purple', 'PURPLE'), ('Orange', 'ORANGE')], default='ORANGE', max_length=200),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='font',
            field=models.TextField(blank=True, choices=[('American', 'AMERICAN'), ('Birckley', 'BIRCKLEY'), ('Brush', 'BRUSH'), ('Comic Sans', 'COMIC SANS'), ('Optima', 'OPTIMA'), ('Spring', 'SPRING'), ('Utopia', 'UTOPIA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='text_align',
            field=models.TextField(blank=True, choices=[('LEFT', 'LEFT'), ('CENTER', 'CENTER'), ('RIGHT', 'RIGHT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
