# Generated by Django 4.1.3 on 2022-11-30 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyena', '0002_remove_socialcard_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_ecards', to='hyena.socialcard'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SocialCard', to='hyena.socialcard'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='border_choices',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='border_color',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='font',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='text_align',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('being_followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OtherUser', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LoggedInUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(fields=('user', 'being_followed'), name='unique_followers'),
        ),
    ]
