# Generated by Django 4.1.3 on 2022-11-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyena', '0002_rename_text_comments_comment_remove_socialcard_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcard',
            name='text_alignment',
            field=models.CharField(blank=True, choices=[('LEFT', 'LEFT'), ('CENTER', 'CENTER'), ('RIGHT', 'RIGHT')], max_length=50, null=True),
        ),
    ]
