# Generated by Django 4.1.3 on 2022-11-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyena', '0003_socialcard_text_alignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialcard',
            old_name='text_alignment',
            new_name='text_align',
        ),
    ]
