# Generated by Django 4.1.3 on 2022-11-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyena', '0004_rename_text_alignment_socialcard_text_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_ecards', to='hyena.socialcard'),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='border_choices',
            field=models.CharField(blank=True, default='solid', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='border_color',
            field=models.CharField(default='white', max_length=100),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='card_color',
            field=models.CharField(default='white', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='font',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='text_align',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
