# Generated by Django 4.1.3 on 2022-11-23 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyena', '0005_alter_socialcard_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SocialCard', to='hyena.socialcard'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='card_color',
            field=models.TextField(max_length=200),
        ),
    ]
