# Generated by Django 4.1.3 on 2022-11-22 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyena', '0005_customuser_favorites_alter_socialcard_border_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SocialCard', to=settings.AUTH_USER_MODEL),
        ),
    ]
