# Generated by Django 4.1.3 on 2022-11-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyena', '0005_alter_socialcard_border_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcard',
            name='border_choices',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='border_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='card_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='font',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='text_align',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
