# Generated by Django 4.1.3 on 2022-11-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyena', '0006_alter_socialcard_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatars'),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='border_choices',
            field=models.CharField(blank=True, choices=[('SOLID', 'Solid'), ('DASHED', 'Dashed'), ('DOTTED', 'Dotted'), ('DOUBLE', 'Double'), ('HAIR', 'Hair'), ('MEDIUM', 'Medium'), ('DASHDOT', 'Dashdot')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='border_color',
            field=models.CharField(choices=[('White', 'WHITE'), ('Red', 'RED'), ('Blue', 'BLUE'), ('Green', 'GREEN'), ('Yellow', 'YELLOW'), ('Pink', 'PINK'), ('Purple', 'PURPLE'), ('Orange', 'ORANGE')], default='ORANGE', max_length=8),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='card_color',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='font',
            field=models.CharField(blank=True, choices=[('American', 'AMERICAN'), ('Birckley', 'BIRCKLEY'), ('Brush', 'BRUSH'), ('Comic Sans', 'COMIC SANS'), ('Optima', 'OPTIMA'), ('Spring', 'SPRING'), ('Utopia', 'UTOPIA')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='text_align',
            field=models.CharField(blank=True, choices=[('LEFT', 'LEFT'), ('CENTER', 'CENTER'), ('RIGHT', 'RIGHT')], max_length=50, null=True),
        ),
    ]
