# Generated by Django 4.1.3 on 2022-11-27 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyena', '0008_alter_follower_follower_alter_follower_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follower',
        ),
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LoggedInUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
