# Generated by Django 4.1.3 on 2022-11-27 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyena', '0009_remove_follower_follower_alter_follower_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='being_followed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OtherUser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
