# Generated by Django 4.1.3 on 2022-11-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyena', '0010_follower_being_followed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='follower',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='card_color',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(fields=('user', 'being_followed'), name='unique_followers'),
        ),
    ]
